//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoadModes.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROAD_LAYERZ
    {
        public int SEG_ID { get; set; }
        public Nullable<int> BEGIN_DIST { get; set; }
        public Nullable<int> END_DIS { get; set; }
        public Nullable<System.DateTime> BUILD_DATE { get; set; }
        public Nullable<int> LAYER_THICK { get; set; }
        public string LAYER__MAT { get; set; }
    }
}
