//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace RoadModes.DB
{
    public partial class TestDB
    {
        public int SEG_ID { get; set; }
        public int BEGIN_DIST { get; set; }
        public int END_DIST { get; set; }
        public DateTime BUILD_DATE { get; set; }
        public int LAYER_THICK { get; set; }
        public string LAYER_MAT { get; set; }
        public DateTime CURDATE { get; set; }
    }
}